name: nodepair_clst
params:
  length_metric:
    - hop
    - physical-length
  sim_metric:
    - physical-length
    - all-one
  linkage_method:
    - single
    - average
    - complete
  n_ref_paths:
    - 5
  threshold:
    - 0.25
    - 0.5
    - 0.75
  beta:
    - 0.0
    - 0.25
    - 0.5
    - 0.75
    - 1.0
